apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/instance: node-js-hello-world-demo
    app.kubernetes.io/name: node-js-hello-world-demo
    pipeline.openshift.io/strategy: docker
    pipeline.openshift.io/type: kubernetes
  name: node-js-hello-world-demo
  namespace: nodejs-demo
spec:
  finally:
    - name: openshift-client
      params:
        - name: SCRIPT
          value: oc get route
        - name: VERSION
          value: latest
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: kubeconfig-dir
          workspace: workspace
        - name: manifest-dir
          workspace: workspace
    - name: argocd-task-sync-and-wait
      params:
        - name: application-name
          value: $(params.APP_NAME)
        - name: revision
          value: HEAD
        - name: flags
          value: '--'
        - name: argocd-version
          value: v2.2.2
      taskRef:
        kind: ClusterTask
        name: argocd-task-sync-and-wait
  params:
    - default: nodejs
      name: APP_NAME
      type: string
    - default: 'https://github.com/Tal-Hason/NodeJS-deployment-demo.git'
      name: GIT_REPO
      type: string
    - default: main
      name: GIT_REVISION
      type: string
    - default: quay.io/thason/node-hello-world
      name: IMAGE_NAME
      type: string
    - default: ContainerFile
      name: PATH_CONTEXT
      type: string
    - default: quay.io/thason/node-hello-world
      name: QUAY_IMAGE
      type: string
    - default: latest
      name: IMAGE_TAG
      type: string
    - default: git-user
      name: SECRET_NAME
      type: string
    - default: nodejs-demo
      name: NAMESPACE
      type: string
    - default: nodejs-app
      name: ARGO_PROJECT
      type: string
  tasks:
    - name: update-chart
      params:
        - name: git-url-source
          value: github.com
        - name: git-user
          value: Tal-Hason
        - name: git-repo-name
          value: NodeJS-deployment-demo
        - name: tag
          value: $(params.IMAGE_TAG)
        - name: branch
          value: $(params.GIT_REVISION)
        - name: git-secret-name
          value: $(params.SECRET_NAME)
      runAfter:
        - build-and-push
      taskRef:
        kind: ClusterTask
        name: update-chart
    - name: update-argocd-app
      params:
        - name: git-url-source
          value: github.com
        - name: git-user
          value: Tal-Hason
        - name: git-repo-name
          value: NodeJS-deployment-demo
        - name: tag
          value: $(params.IMAGE_TAG)
        - name: branch
          value: $(params.GIT_REVISION)
        - name: git-secret-name
          value: $(params.SECRET_NAME)
        - name: namespace
          value: $(params.NAMESPACE)
        - name: git-full-url
          value: $(params.GIT_REPO)
        - name: application-name
          value: $(params.APP_NAME)
        - name: project-name
          value: $(params.ARGO_PROJECT)
      runAfter:
        - update-chart
      taskRef:
        kind: ClusterTask
        name: update-argocd-app
    - name: update-argocd-proj
      params:
        - name: git-url-source
          value: github.com
        - name: git-user
          value: Tal-Hason
        - name: git-repo-name
          value: NodeJS-deployment-demo
        - name: tag
          value: $(params.IMAGE_TAG)
        - name: branch
          value: $(params.GIT_REVISION)
        - name: project-name
          value: $(params.ARGO_PROJECT)
        - name: git-secret-name
          value: $(params.SECRET_NAME)
        - name: namespace
          value: $(params.NAMESPACE)
        - name: git-full-url
          value: $(params.GIT_REPO)
      runAfter:
        - update-chart
      taskRef:
        kind: ClusterTask
        name: update-argocd-proj
    - name: build-and-push
      params:
        - name: git-url-source
          value: github.com
        - name: git-user
          value: Tal-Hason
        - name: git-repo-name
          value: NodeJS-deployment-demo
        - name: tag
          value: $(params.IMAGE_TAG)
        - name: branch
          value: $(params.GIT_REVISION)
        - name: git-secret-name
          value: $(params.SECRET_NAME)
        - name: namespace
          value: $(params.NAMESPACE)
        - name: git-full-url
          value: $(params.GIT_REPO)
        - name: project-name
          value: $(params.ARGO_PROJECT)
        - name: application-name
          value: $(params.APP_NAME)
        - name: image_name
          value: $(params.IMAGE_NAME)
      runAfter:
        - clean-chart
      taskRef:
        kind: ClusterTask
        name: build-and-push
    - name: clean-chart
      params:
        - name: git-url-source
          value: github.com
        - name: git-user
          value: Tal-Hason
        - name: git-repo-name
          value: NodeJS-deployment-demo
        - name: tag
          value: $(params.IMAGE_TAG)
        - name: branch
          value: $(params.GIT_REVISION)
        - name: git-secret-name
          value: $(params.SECRET_NAME)
        - name: namespace
          value: $(params.NAMESPACE)
        - name: git-full-url
          value: $(params.GIT_REPO)
        - name: project-name
          value: $(params.ARGO_PROJECT)
        - name: application-name
          value: $(params.APP_NAME)
        - name: image_name
          value: $(params.IMAGE_NAME)
      taskRef:
        kind: ClusterTask
        name: clean-chart
  workspaces:
    - name: workspace
