apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: node-js-hello-world-demo-5ebon5
  namespace: nodejs-demo
  labels:
    app.kubernetes.io/instance: pipeline-tasks
    app.kubernetes.io/name: node-js-hello-world-demo
    pipeline.openshift.io/strategy: docker
    pipeline.openshift.io/type: kubernetes
    tekton.dev/pipeline: node-js-hello-world-demo
spec:
  params:
    - name: APP_NAME
      value: nodejs
    - name: GIT_REPO
      value: 'https://github.com/Tal-Hason/NodeJS-deployment-demo.git'
    - name: GIT_REVISION
      value: main
    - name: IMAGE_NAME
      value: quay.io/thason/node-hello-world
    - name: PATH_CONTEXT
      value: .
    - name: QUAY_IMAGE
      value: quay.io/thason/node-hello-world
    - name: IMAGE_TAG
      value: latest
    - name: SECRET_NAME
      value: git-user
    - name: NAMESPACE
      value: nodejs-demo
    - name: ARGO_PROJECT
      value: nodejs-app
    - name: APP_OF_APPS
      value: argocd-application-folder
  pipelineRef:
    name: node-js-hello-world-demo
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: workspace
status:
  completionTime: '2022-08-04T10:18:53Z'
  conditions:
    - lastTransitionTime: '2022-08-04T10:18:53Z'
      message: 'Tasks Completed: 7 (Failed: 0, Cancelled 0), Skipped: 0'
      reason: Succeeded
      status: 'True'
      type: Succeeded
  pipelineSpec:
    finally:
      - name: openshift-client
        params:
          - name: SCRIPT
            value: oc get route
          - name: VERSION
            value: latest
        taskRef:
          kind: ClusterTask
          name: openshift-client
        workspaces:
          - name: kubeconfig-dir
            workspace: workspace
          - name: manifest-dir
            workspace: workspace
