apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xxxAppNamexxx
  namespace: openshift-gitops
spec:
  destination:
    namespace: xxxNameSpacexxx
    server: 'https://kubernetes.default.svc'
  project: xxxProjectNamexxx
  source:
    path: ./Helm
    repoURL: xxxRepoUrlxxx
    targetRevision: xxxBranchxxx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true