apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: xxxProjectNamexxx
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: '*'
      namespace: '*'
      server: 'https://kubernetes.default.svc'
    - name: in-cluster
      namespace: xxxNameSpacexxx
      server: 'https://kubernetes.default.svc'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
status: {}
