apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs
  namespace: openshift-gitops
spec:
  destination:
    namespace: nodejs-demo
    server: 'https://kubernetes.default.svc'
  project: nodejs-demo
  source:
    path: ./Helm
    repoURL: https://github.com/Tal-Hason/NodeJS-deployment-demo.git
    targetRevision: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true